cmake_minimum_required(VERSION 3.16)
project(ellipselio_live_launcher LANGUAGES CXX)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_components REQUIRED)
find_package(class_loader REQUIRED)
add_executable(ellipselio_mapping_mt node_main.cpp)
target_compile_features(ellipselio_mapping_mt PRIVATE cxx_std_17)
ament_target_dependencies(ellipselio_mapping_mt rclcpp rclcpp_components class_loader)
