/**:
  ros__parameters:
    mapping:
      map_resolution: 0.1
      pub_map_n_secs: 10
      namespace: Carol
    publish:
      map: false
      scan: false
      markers: false
      odometry: true
      analytics: false
      tf: false
    lidar:
      type: 2
      rate: 10
      scan_lines: 16
      vertical_fov: 30.0
      min_range: 1.0
      max_range: 100.0
      topic: /Carol/velodyne_points
      t_imu_lidar:
      - -0.03181799390095727
      - -0.0050584361631037245
      - 0.20284730569079368
      r_imu_lidar:
      - 0.9996571430423355
      - 0.020396103869417127
      - 0.01641957545551314
      - -0.020033102981335992
      - 0.9995577585857329
      - -0.02197625725243218
      - -0.016860545614981855
      - 0.021639784965623222
      - 0.9996236544083085
    imu:
      rate: 100
      acc_noise: 0.011692699862662088
      gyr_noise: 0.010216647894856925
      acc_bias: 0.0002041305895172543
      gyr_bias: 8.45143056189658e-05
      topic: /Carol/imu/data
    cameras:
      num_cams: 0
    input:
      reliable: true
    use_sim_time: true
    research:
      enabled: true
      robot: Carol
      python: /workspace/.ros2/research-venv/bin/python
      writer: /workspace/FAST-LIVO2-ROS2/research/s3e_pipeline/mcap_writer.py
      output: /workspace/.ros2/swarm148/library1/frontend/Carol/export
